hydra:
  run:
    dir: /lustre/fsn1/projects/rech/oou/ucy22cr/pantagruel/tmp/hydra/outputs/${hydra.job.name}/${hydra.job.num}
  sweep:
    dir: /lustre/fsn1/projects/rech/oou/ucy22cr/pantagruel/tmp/hydra/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

common:
  fp16: true
  log_format: json
  log_interval: 500
  tensorboard_logdir: ???
  fp16_no_flatten_grads: true
  # user_dir: ${env:PWD}/examples/data2vec
  time_limit: ???

checkpoint:
  # save_interval: 1
  # save_interval_updates: 50000
  # keep_interval_updates: 1
  # no_epoch_checkpoints: true
  # keep_best_checkpoints: 10
  # keep_last_epochs: 10
  # patience: 10
  save_dir: ???

distributed_training:
  distributed_world_size: ???
  ddp_backend: no_c10d
  distributed_port: ???

task:
  _name: masked_lm
  data: ???
  sample_break_mode: complete
  tokens_per_sample: 512
  include_target_tokens: true
  random_token_prob: 0
  leave_unmasked_prob: 0
  include_index: True
  skip_masking: True
  d2v2_multi: True
  mask_idx_in_vocab: True
  bos_token_prepended: True
  pantagruel_multi: True

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var
    - pred_var
    - model_norm
    - ema_norm
    - masked_pct

dataset:
  num_workers: 3
  max_tokens: 16384
  # batch_size: 32
  # batch_size_valid: 6
  # ignore_unused_valid_subsets: true
  skip_invalid_size_inputs_valid_test: true
  # disable_validation: true

optimization:
  clip_norm: 1
  lr: [0.0005]
  max_update: 125000
  update_freq: [1]
  # max_epoch: 5

optimizer:
  _name: composite
  dynamic_groups: true
  groups:
    default:
      lr_float: 0.0005
      optimizer:
        _name: adam
        adam_betas: [0.9,0.98]
        adam_eps: 1e-06
        weight_decay: 0.01
      lr_scheduler:
        _name: cosine
        warmup_updates: 4000 # larger warmup (from 4k) as LR increases
    mlm_head:
      lr_float: 0.00001
      optimizer:
        _name: adam
        adam_betas: [0.9,0.98]
        adam_eps: 1e-06
        weight_decay: 0.01
      lr_scheduler:
        _name: cosine
        warmup_updates: 4000

lr_scheduler: pass_through

model:
  _name: data2vec_multi

  loss_beta: 0
  loss_scale: 1

  d2v_loss: 1.0
  mlm_loss: 0.005
  mlm_num_layers: 6
  mlm_decay_steps: 100000
  mlm_start_ratio: 1.0
  mlm_group: true

  # std_coeff: 0.1
  # cov_coeff: 0.1

  depth: 12
  embed_dim: 768
  clone_batch: 8

  ema_decay: 0.9995
  ema_end_decay: 0.9999
  ema_anneal_end_step: 50000
  ema_encoder_only: true

  average_top_k_layers: 12
  layer_norm_target_layer: false
  instance_norm_target_layer: true
  batch_norm_target_layer: false
  instance_norm_targets: false
  layer_norm_targets: false

  layerdrop: 0
  norm_eps: 1e-5

  supported_modality: TEXT

  modalities:
    text:
      mask_prob: 0.6
      mask_length: 3
      mask_noise_std: 0.01
      prenet_depth: 0
      decoder:
        input_dropout: 0.1
        decoder_dim: 768
        decoder_groups: 1
        decoder_kernel: 9
        decoder_layers: 5
        decoder_residual: false
        projection_layers: 2
        projection_ratio: 2.0